services:
  - type: web
    name: potent-backend
    env: python
    buildCommand: pip install Django gunicorn psycopg2-binary djangorestframework
    startCommand: gunicorn potent.wsgi:application
    plan: free
