services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: your-subdomain.onrender.com
